on:
  schedule:
    - cron: "/5 * * * *"
    
jobs:
  test_schedule:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./scripts
    steps:
      - name: Every time
        run: Helldiver Archivist.js
